[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "linalg"
version = "1.8"
description = "Linear algebra with scalar object support & progress visualisation."
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
  {name="Sebastian Gössl", email="goessl@student.tugraz.at"}
]
dependencies = [
  "numpy",
  "tqdm",
  "iteration @ git+https://github.com/goessl/iteration.git"
]

[project.urls]
Homepage = "https://github.com/goessl/linalg"
Documentation = "https://goessl.github.io/linalg"
Repository = "https://github.com/goessl/linalg.git"

[project.optional-dependencies]
test = ["pytest", "sympy"]
